INSERT INTO beans (id, roaster, name, origin, date_purchased, notes, great_on) VALUES
  (1, 'Spaceboy', 'Wilder Garcia', 'Peru', '2026-04-21',
   '["Stonefruit","Herbaceous","Caramel","Mango"]'::jsonb,
   '["Pour Over","Espresso","Latte"]'::jsonb),
  (2, 'Unorthodox', 'Wee Stoater', 'Brazil', '2026-05-15',
   '["Chocolate","Hazelnut","Caramel"]'::jsonb,
   '["Pour Over","Latte","Aeropress"]'::jsonb),
  (3, 'Square Mile', 'Red Brick', 'Ethiopia', '2026-03-10',
   '["Forest fruits","Cherry","Almond","Fudge"]'::jsonb,
   '["Espresso"]'::jsonb),
  (4, 'Hej', 'Caffe Queero', 'Colombia', '2021-03-02',
   '["Cranberry","Biscuit","Honey"]'::jsonb,
   '["Pour Over","Aeropress"]'::jsonb),
  (5, 'Rode & Grind', 'Rocket Fuel', 'Blend', '2026-02-14',
   '["Hazelnut","Caramel","Dark Chocolate"]'::jsonb,
   '["Pour Over","Latte"]'::jsonb),
  (6, 'Unorthodox', 'Ultimate Stoater', 'Brazil', '2026-04-05',
   '["Banana","Honey","Golden Raisin"]'::jsonb,
   '["Pour Over","Latte","Espresso"]'::jsonb),
  (7, 'Dear Green', 'Fazenda Pantano', 'Brazil', '2021-09-27',
   '["Chocolate","Caramel","Peanut"]'::jsonb,
   '["Espresso","Latte"]'::jsonb),
  (8, 'Artisan Roast', 'Santa Monica', 'Peru', '2022-05-18',
   '["Orange","Milk chocolate","Dried Fruit"]'::jsonb,
   '["Aeropress"]'::jsonb),
  (9, 'Spaceboy', 'Cosmic Drift', 'Colombia', '2026-05-01',
   '["Raspberry","Lime","Honeysuckle"]'::jsonb,
   '["Pour Over"]'::jsonb),
  (10, 'Fortitude', 'Worka Wuri', 'Ethiopia', '2026-04-10',
   '["Peach","Lemon","Dried Fruit"]'::jsonb,
   '["Espresso","Latte"]'::jsonb),
  (11, 'Cairngorm', 'Sweetdrop', 'Brazil', '2026-03-19',
   '["Dark Chocolate","Brown Sugar","Bold"]'::jsonb,
   '["Pour Over","Aeropress","Latte"]'::jsonb),
  (12, 'DAK', 'Milky Cake', 'Colombia', '2025-05-27',
   '["Cardamom","Pistachio","Vanilla cake"]'::jsonb,
   '["Latte"]'::jsonb)
ON CONFLICT (id) DO NOTHING;
